# Generated by Django 3.0.8 on 2020-08-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indx', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
