# Generated by Django 3.0.8 on 2020-08-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indx', '0003_app_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App_user',
        ),
    ]
