# Generated by Django 3.0.8 on 2020-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indx', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='indx/images/'),
        ),
    ]
