# Generated by Django 3.0.8 on 2020-08-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indx', '0006_auto_20200813_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
    ]
