# Generated by Django 3.1 on 2020-08-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indx', '0007_remove_product_product_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
