# Generated by Django 3.1 on 2020-08-28 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indx', '0009_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
