# Generated by Django 3.1 on 2020-08-28 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indx', '0012_bot_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='date',
        ),
        migrations.AddField(
            model_name='bot',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
